### This is just to follow along and play around with numpy

In [16]:
import numpy as np

In [17]:
ar1 = np.array([1, 2, 3])


In [18]:
type(ar1)


numpy.ndarray

In [19]:
ar2 = np.array([[1, 2.0, 3.3],
               [4.5, 5, 6.7]])

In [20]:
ar3 = np.array([
    [
        [1, 2, 3, 5],
        [4, 5, 6, 5],
        [7, 8, 9, 5]
    ],
    [
        [10, 11, 12, 5],
        [13, 14, 15, 5],
        [16, 17, 18, 5]
    ]
])

In [21]:
ar2

array([[1. , 2. , 3.3],
       [4.5, 5. , 6.7]])

In [22]:
ar3

array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  5],
        [ 7,  8,  9,  5]],

       [[10, 11, 12,  5],
        [13, 14, 15,  5],
        [16, 17, 18,  5]]])

### the shape of ar3 is (2, 3, 4), see the formatting above where it's declared

In [23]:
ar3.shape

(2, 3, 4)

In [24]:
ar1.shape


(3,)

In [25]:
#ndarray.ndim tells you how many dimensions are present in the ndarray
ar1.ndim, ar2.ndim, ar3.ndim

(1, 2, 3)

In [26]:
ar1.dtype, ar2.dtype, ar3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [27]:
#.size gives us the total number of elements are in the ndarray
ar1.size, ar2.size,ar3.size


(3, 6, 24)

In [28]:
#these vary by shape and num of dimensions, but they're all ndarray datatypes
type(ar1), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a pandas DataFrame from a NumPy array


In [29]:
import pandas as pd
df = pd.DataFrame(ar2)
df

0    1    2
0  1.0  2.0  3.3
1  4.5  5.0  6.7

In [30]:
#This does not work, you have to pass a 2d input to the DataFrame
# df3 = pd.DataFrame(ar3)
# df3

In [31]:
#However, passing a 1d ndarray does work, you just get a vector visualization
df1 = pd.DataFrame(ar1)
df1


0
0  1
1  2
2  3

In [32]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
type(ones)

numpy.ndarray

In [34]:
range_array = np.arange(0, 11, 2)

In [35]:
range_array

array([ 0,  2,  4,  6,  8, 10])

In [36]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 3, 9, 7, 1],
       [6, 1, 5, 6, 5],
       [6, 8, 1, 4, 5]])

In [39]:
ar3


array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  5],
        [ 7,  8,  9,  5]],

       [[10, 11, 12,  5],
        [13, 14, 15,  5],
        [16, 17, 18,  5]]])

In [43]:
ar3[1, :2]

array([[10, 11, 12,  5],
       [13, 14, 15,  5]])

In [44]:
big_array = np.random.randint(0, 145, (3, 4, 5, 6))

In [45]:
big_array

array([[[[ 90,  74, 100,  56, 136,  67],
         [ 25,  36, 107,  76,  16,  28],
         [131, 138,  35,  73,  99, 111],
         [ 34,  81,  60,  55,  80,  79],
         [113,  73,  91,   6,  99, 106]],

        [[117, 142,  51,  92,  64,  15],
         [ 76,  87,  72,  55, 125, 122],
         [ 79, 115,  13, 103,  36,  36],
         [ 76, 126,  12,  60, 143,  71],
         [124, 141,  27,  77,  28, 111]],

        [[132,  86, 130,  32, 124, 121],
         [121,   4,  64,  83,  36,  11],
         [139, 119,  79,  18,  99,  36],
         [ 36, 123, 134,  27,  58,  54],
         [  1,  71,  33,  91,  68,  16]],

        [[ 66,   5,   6,  69,  83,   3],
         [ 79,  72,  71,  62,  75, 116],
         [ 24, 137, 128,   7, 144, 118],
         [137,  30,  44,  40,  13,   1],
         [ 52,  60,  52, 124,  83,  37]]],


       [[[ 18,  90,  18,  89, 133, 104],
         [ 80,  97,  10,  32, 128, 101],
         [ 18,  17,  56, 142,  93,  35],
         [ 84,  61, 100, 118, 110, 115],
      

In [46]:
big_array[:, :, :, :3]

array([[[[ 90,  74, 100],
         [ 25,  36, 107],
         [131, 138,  35],
         [ 34,  81,  60],
         [113,  73,  91]],

        [[117, 142,  51],
         [ 76,  87,  72],
         [ 79, 115,  13],
         [ 76, 126,  12],
         [124, 141,  27]],

        [[132,  86, 130],
         [121,   4,  64],
         [139, 119,  79],
         [ 36, 123, 134],
         [  1,  71,  33]],

        [[ 66,   5,   6],
         [ 79,  72,  71],
         [ 24, 137, 128],
         [137,  30,  44],
         [ 52,  60,  52]]],


       [[[ 18,  90,  18],
         [ 80,  97,  10],
         [ 18,  17,  56],
         [ 84,  61, 100],
         [123,  83,   1]],

        [[118,  48,  62],
         [ 22, 109,  30],
         [101, 120,  13],
         [117,  12,  94],
         [ 31,  51, 117]],

        [[124,  85, 115],
         [108,  73, 119],
         [ 18, 117, 122],
         [121,  64,  23],
         [ 60, 108, 128]],

        [[ 18, 105,  50],
         [ 18,  16, 130],
         [112,  62,  7